name: Release
on:
  push:
    tags: ['v*']
jobs:
  build:
    uses: oprobiu/AFAS/.github/workflows/build-release.yml@v0.0.3
    with:
      tools-version: v0.0.3
    permissions:
      contents: write
